#!/bin/bash

ls -l $* | awk '
BEGIN {print "BYTES", "\t", "FILE"}

NF == 9 && /^-/ {
	sum += $5
	++filesum
#	print $5, "\t", $9
	printf("|%-15s|%10d|\n", $9, $5)
}

NF ==9 && /^d/ {
	print "<dir>", "\t", $9
}

END {
	print "Total:", sum, "bytes (", filesum, "files)"
}
'
